add sync editor
stolostron/console pull request #1228
Opened 2022-02-21 18:30 UTC by jeswanke

Signed-off-by: John Swanke <jswanke@redhat.com>

2022-02-22 22:08 UTC, KevinFCormier commented
/cc @jamestalton

2022-02-22 22:27 UTC, KevinFCormier commented
@jeswanke I found a few issues.

1. The **Editor changes** section uses a 14px heading, which is the same as the label on fields. I think this might need to be 20px to match the section headings, and some feedback from design might be useful.
1. Secrets are not hidden in the **Editor changes** section if I reveal them, make changes, then hide them again.
1. Edit credential fails on submit.

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/42188127/155229857-764233e9-4e4c-4dc9-b5ad-65512f6420c8.png">

```
TypeError
Cannot read properties of null (reading 'getAllDecorations')
Call Stack
 getResourceEditorDecorations
  src/components/SyncEditor/decorate.ts:111:10
 decorate
  src/components/SyncEditor/decorate.ts:24:60
 eval
  src/components/SyncEditor/SyncEditor.tsx:246:64
```

<img width="1783" alt="image" src="https://user-images.githubusercontent.com/42188127/155230063-939af3f1-c92c-4662-a2a8-995dc5274955.png">

2022-02-24 01:15 UTC, KevinFCormier commented
@jeswanke Thanks for the updates. It's much closer now, except that the secret is not actually updated when I edit. The page does not crash and I get the toast saying it was successful, but it is not actually changed.

2022-02-24 21:18 UTC, KevinFCormier requested changes
@jeswanke I requested you externalize your strings. Also, when YAML editing is off and you go to create/edit/view a Credential, the drawer starts to pop out for a moment before it hides itself. That seems like a bug.

2022-02-24 21:18 UTC, KevinFCormier commented on frontend/src/components/AcmDataForm.tsx
> +const EDITOR_CHANGES = 'Editor changes'
Can we externalize this string, please?

2022-02-25 15:58 UTC, jeswanke commented on frontend/src/components/AcmDataForm.tsx
> +const EDITOR_CHANGES = 'Editor changes'
ok, now t( )

2022-02-28 13:53 UTC, closed without merging