RHV provider label detection logic added
stolostron/console pull request #1348
Opened 2022-03-16 17:28 UTC by Randy424

Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>

2022-03-16 17:31 UTC, Randy424 commented
/cc @KevinFCormier 
FYI @dtthuynh

2022-03-16 19:19 UTC, KevinFCormier requested changes
There's at least one other place where we map the providers that this PR doesn't cover:
https://github.com/stolostron/console/blob/main/frontend/src/routes/Home/Overview/OverviewPage.tsx#L43

Ideally these should share the same code.

Once that is done, on the Overview page, you'll need to hook up the display name for RHV as well:
<img width="1740" alt="image" src="https://user-images.githubusercontent.com/42188127/158671034-e0327514-08ee-425e-884e-4aaef4d7a936.png">

2022-03-17 18:46 UTC, Randy424 commented
- PR for the display name change is up.
- Provider detection function used in Overview has now been replaced with shared util function

2022-03-17 18:54 UTC, KevinFCormier commented on frontend/src/routes/Home/Overview/OverviewPage.tsx
> -        case 'vmware':
Can we move the VMWARE case to the new code?

2022-03-17 19:53 UTC, KevinFCormier commented
/lgtm

2022-03-17 20:56 UTC, merged