Bug 2071750: Fix nmstate labeling
stolostron/console pull request #1594
Opened 2022-04-26 10:36 UTC by jtomasek

- use nmStates as recoil atoms
- fix finding matching nmstates to infraenv and baremetal host
- fix deleting nmstates when deleting baremetal hosts

Fixes BZ2071750
Depends on https://github.com/openshift-assisted/assisted-ui-lib/pull/1326

Signed-off-by: Jiri Tomasek <jtomasek@redhat.com>

2022-04-27 07:28 UTC, rawagner requested changes

2022-04-27 07:28 UTC, rawagner commented on frontend/src/routes/Infrastructure/InfraEnvironments/utils.ts
> +    ['BareMetal', 'None', 'OpenStack', 'VSphere', 'AWS'].includes(infrastructure?.status?.platform)
AWS sneaking in again!

```suggestion
    ['BareMetal', 'None', 'OpenStack', 'VSphere'].includes(infrastructure?.status?.platform)
```

2022-04-27 14:41 UTC, jtomasek commented on frontend/src/routes/Infrastructure/InfraEnvironments/utils.ts
> +    ['BareMetal', 'None', 'OpenStack', 'VSphere', 'AWS'].includes(infrastructure?.status?.platform)
Done

2022-04-28 06:31 UTC, rawagner approved these changes

2022-04-28 06:31 UTC, rawagner commented
/lgtm

2022-04-28 07:01 UTC, merged