Merge translation files from assisted-ui-lib into one file
stolostron/console pull request #1710
Opened 2022-05-24 12:30 UTC by ammont82

Related to https://github.com/openshift-assisted/assisted-ui-lib/pull/1399/

Related to https://issues.redhat.com/browse/MGMT-8156

Signed-off-by: Montse Ortega <mortegag@redhat.com>

2022-05-24 13:45 UTC, KevinFCormier commented
@ammont82 Is this a work in progress? I have some questions and potentially some changes to request once it is ready for review.

2022-05-24 15:00 UTC, KevinFCormier requested changes
Thanks Montse! This looks great.

I think the files under `locales_merged` should be added to `.gitignore` and not committed.

2 other suggestions made inline.

2022-05-25 05:19 UTC, ammont82 commented on frontend/webpack.plugin.ts
> +              }),
Yes, I can review and try to handle each locale

2022-05-25 05:19 UTC, ammont82 commented on package.json
> +        "merge-jsons-webpack-plugin": "^2.0.1"
Ok, I can change

2022-05-27 11:53 UTC, rawagner commented on frontend/webpack.plugin.ts
> +                    "fileName": `../../../public/locales/${locale}/translation.json`
```suggestion
                        "fileName": `../../../public/locales/${locale}/translation.json`
```

2022-06-27 07:56 UTC, rawagner commented
/ok-to-test

2022-06-27 09:52 UTC, rawagner commented
/lgtm

2022-06-27 09:54 UTC, merged