Bug 2091825 - if a host in infra env is in "disconnected" status, there is no indication of it in the list view
stolostron/console pull request #1757
Opened 2022-06-16 10:50 UTC by ammont82

Related to https://bugzilla.redhat.com/show_bug.cgi?id=2091825

2022-06-21 13:34 UTC, jtomasek commented
/ok-to-test

2022-06-21 13:35 UTC, jtomasek requested changes

2022-06-21 13:35 UTC, jtomasek commented on frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
> +                                    'insufficient-unbound',
```suggestion
                                    'insufficient-unbound',
                                    'disconnected',
```

2022-06-22 05:09 UTC, ammont82 commented on frontend/src/routes/Infrastructure/InfraEnvironments/InfraEnvironmentsPage.tsx
> +                                    'insufficient-unbound',
changes done!

2022-06-22 10:07 UTC, jtomasek approved these changes
/lgtm

2022-06-22 10:22 UTC, merged