Cluster labels section does not show up#22433
stolostron/console pull request #1800
Opened 2022-07-01 13:10 UTC by jeswanke

2022-07-05 22:59 UTC, KevinFCormier requested changes
Please make sure the labels for PlacementRules with `spec.clusterSelector.matchLabels` get substituted into the PR description and that it works for multiple labels. What happens if there are say 5+ labels? It looks like you are trying to handle `spec.clusterSelector.matchExpressions` - the backend does support this, but it looks like the UI has never understood PlacementRules in that form.

Discussion on the labels is also still ongoing.

2022-07-06 16:11 UTC, KevinFCormier reviewed
I added comments for the changes needed. In addition there is this one:
```
"creation.app.placement.rule": "Select clusters for application deployment",
```

2022-07-06 16:11 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +    "creation.app.clusters.matching": "{{0}} deploys to clusters clusters with these labels: {{1}}",
Word "clusters" is duplicated

2022-07-06 16:11 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +    "creation.app.settings.onlineClusters": "Deploy to any online clusters and local cluster",
Keep "all" instead of "any"

2022-07-06 16:11 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +    "creation.app.clusters.all.online": "{{0}} deploys to any online clusters and local cluster",
There should be 2 versions of this similar to `creation.app.settings.onlineClustersOnly` and `creation.app.settings.onlineClusters` that switch based on whether hub self management is enabled.

2022-07-06 16:11 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +    "creation.app.settings.clusterSelector": "Create a placement configuration to deploy on clusters with specified labels",
Change to "Deploy application resources on clusters with all specified labels"

2022-07-06 16:11 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +    "creation.app.clusters.all.online": "{{0}} deploys to any online clusters and local cluster",
And "any" should be "all"

2022-07-06 16:11 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
>      "creation.app.settings.existingRule": "Select an existing placement configuration",
Please look into why we have this string twice!

2022-07-06 19:07 UTC, jeswanke commented
@KevinFCormier  -- for this one: https://github.com/stolostron/console/pull/1800#pullrequestreview-1029299051

matchLabels work as long as the key is unique--if a user wanted to say cloud=aws and azure, they would need matchExpressions--iow they can't do:
  matchLabels:
     cloud: 'AWS'
     cloud: 'AZR'

2022-07-07 00:03 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +    "creation.app.clusters.all.online": "{{0}} deploys to any online clusters and local cluster",
First comment not addressed.

2022-07-07 00:21 UTC, KevinFCormier commented
> @KevinFCormier -- for this one: [#1800 (review)](https://github.com/stolostron/console/pull/1800#pullrequestreview-1029299051)
> 
> matchLabels work as long as the key is unique--if a user wanted to say cloud=aws and azure, they would need matchExpressions--iow they can't do: matchLabels: cloud: 'AWS' cloud: 'AZR'

For a PlacementRule with multiple matchLabels:
```
spec:
  clusterSelector:
    matchLabels:
      foo: bar
      good: bye
      "yes": "no"
```

I see:
<img width="950" alt="image" src="https://user-images.githubusercontent.com/42188127/177663431-431cfd60-b825-4446-a728-5a0bdb8efe51.png">

`matchLabels` is not an array, and your code is trying to substitute the first element of the array.

As I mentioned, I don't think matchExpressions has ever been supported in the UI. It might be good to support it, but your code ignores the `operator` value and uses `=` for everything.

2022-07-08 14:38 UTC, KevinFCormier commented on frontend/src/routes/Applications/CreateApplication/Subscription/controlData/ControlDataPlacement.js
> +                                    return `${key}${operator === 'In' ? '=' : '!='}${values.join(', ')}`
This does not account for the `Exists` and `DoesNotExist` values for `operator`.

```
properties:
                  matchExpressions:
                    description: matchExpressions is a list of label selector requirements. The requirements are ANDed.
                    items:
                      description: A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
                      properties:
                        key:
                          description: key is the label key that the selector applies to.
                          type: string
                        operator:
                          description: operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
                          type: string
                        values:
                          description: values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
```

2022-07-08 14:39 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +    "creation.app.clusters.all.online": "{{0}} deploys to any online clusters and local cluster",
Fixed now.

2022-07-08 14:53 UTC, KevinFCormier commented
/hold

2022-07-08 14:58 UTC, KevinFCormier commented
Thanks for all the fixes. I have a few other minor concerns.

1. When using an existing placement rule that matches by labels, the label controls are filled in when you first enter the editor (as in the first repository in this screenshot) but not if you change to one that does (as in the 2nd repository in this screenshot).
2. The delete button for the repository does not work with the new styling you added.
3. `operator` value still not handled properly for `matchExpressions`.

![image](https://user-images.githubusercontent.com/42188127/178017837-f8a36013-67ab-4e09-bc13-92758aa27504.png)

I have put a hold on this PR because I think @fxiang1 or @chenz4027 should also review this since it's in the app lifecycle UI. I'll leave the remainder of the review to them.

2022-07-08 14:59 UTC, KevinFCormier commented
/lgtm

2022-07-08 19:29 UTC, fxiang1 approved these changes
LGTM!

2022-07-11 18:25 UTC, chenz4027 approved these changes
lgtm

2022-07-11 18:33 UTC, KevinFCormier commented
/unhold

2022-07-11 18:35 UTC, merged