Added fields for vSphere Folder and ResourcePool
stolostron/console pull request #1803
Opened 2022-07-02 14:12 UTC by briantward

Adds the vSphere folder and vSphere resource pool variables that are found in the `install-config.yaml` to the ACM UI.

https://docs.openshift.com/container-platform/4.10/installing/installing_vsphere/installing-vsphere-installer-provisioned-customizations.html#installation-installer-provisioned-vsphere-config-yaml_installing-vsphere-installer-provisioned-customizations

2022-07-02 14:46 UTC, briantward commented
I've tested this with expectations that it populates over to the install-config.yaml correctly; however, I've not personally tested it end to end with a custom folder and resource pool.  Also, I'd like to confirm that it works correctly with spaces in object names.

I'm interested in feedback from the development team.  We have a customer looking for this feature, and we'll open a BZ for it shortly.

Oh, and I did notice after the fact that install-config.yaml also offers another field we are missing: diskType.  That might be a quick addition.

2022-07-06 13:04 UTC, KevinFCormier commented
/ok-to-test

2022-07-06 15:06 UTC, KevinFCormier commented on frontend/src/routes/Credentials/CredentialsForm.test.tsx
> +                resourcePool: 'resourcePool'
Thanks for the contribution! Please let me know when a Bugzilla is opened and if you'd like to continue working on this PR or if you'd like us to put the finishing touches on it ourselves. Tests failed with:
```
[frontend] [prettier] [error] src/routes/Credentials/CredentialsForm.test.tsx: SyntaxError: ',' expected. (212:17)
[frontend] [prettier] [error]   210 |                 folder: 'folder',
[frontend] [prettier] [error]   211 |                 resourcePool: 'resourcePool'
[frontend] [prettier] [error] > 212 |                 imageContentSources: '',
[frontend] [prettier] [error]       |                 ^
[frontend] [prettier] [error]   213 |             },
[frontend] [prettier] [error]   214 |             true
[frontend] [prettier] [error]   215 |         )
```

2022-10-07 22:25 UTC, KevinFCormier commented
@cadawson Could you please review the changes to `frontend/public/locales/en/translation.json` when you have a moment - or delegate to appropriate person on docs team. Thanks!

2022-10-11 18:18 UTC, KevinFCormier commented
/cc @jeswanke

2022-10-11 19:04 UTC, cadawson requested changes
A couple of suggestions, but looks good. Thanks!

2022-10-11 19:04 UTC, cadawson commented on frontend/public/locales/en/translation.json
> +    "Enter your vSphere folder absolute path": "Enter your vSphere folder absolute path",
Could also use: "Enter the absolute path to your vSphere folder": "Enter the absolute path to your vSphere folder"

2022-10-11 19:04 UTC, cadawson commented on frontend/public/locales/en/translation.json
> +    "Enter your vSphere resource pool absolute path": "Enter your vSphere resource pool absolute path",
Similarly: "Enter the absolute path to your vSphere resource pool": "Enter the absolute path to your vSphere resource pool"

2022-10-12 13:14 UTC, KevinFCormier commented
> @KevinFCormier thanks for the progress on this rfe/pr. I see you caught that hive ClusterDeployment doesn't have the resourcepool field. What implication would that have downstream, since (it appears to me) the console is also generating its own install-config.yaml ?

@briantward If we add `resourcePool` to the `ClusterDeployment`, it is not saved in the resource. But we are still putting it in the `install-config.yaml` which Hive will use during provisioning, so I think it should work. 

Does that answer your question? I don't really understand your reference to "downstream" here.

2022-10-12 13:19 UTC, briantward commented
> > @KevinFCormier thanks for the progress on this rfe/pr. I see you caught that hive ClusterDeployment doesn't have the resourcepool field. What implication would that have downstream, since (it appears to me) the console is also generating its own install-config.yaml ?
> 
> @briantward If we add `resourcePool` to the `ClusterDeployment`, it is not saved in the resource. But we are still putting it in the `install-config.yaml` which Hive will use during provisioning, so I think it should work.
> 
> Does that answer your question? I don't really understand your reference to "downstream" here.

@KevinFCormier that answers my question. I only meant downstream execution logic. I could also open an RFE to update the ClusterDeployment API to be in sync with install-config, even if it isn't strictly needed here. I'm not sure how much it matters to that team or other integrations.

2022-10-12 13:58 UTC, jeswanke approved these changes

2022-10-12 14:04 UTC, merged