Handle clusters with different name and namespace
stolostron/console pull request #2157
Opened 2022-10-04 08:42 UTC by rawagner

Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

2022-10-06 07:54 UTC, rawagner commented
@KevinFCormier can you take a look ?

2022-11-22 20:34 UTC, KevinFCormier requested changes
Import flow is not working with this code. I get redirected back to the cluster list instead of the details page for the newly imported cluster. I noticed that you set namespace to `~managed-cluster` for the import redirect, but this means we will not find the `ManagedClusterInfo`. So I tried changing it to match the name, but I guess there is still something not being found on the ClusterDetails page.

A couple other inline comments as well.

2022-11-23 08:50 UTC, rawagner commented on frontend/src/resources/utils/get-cluster.ts
> +        isHive: !!clusterDeployment,
not really, i removed the change

2022-11-23 08:51 UTC, rawagner commented
@KevinFCormier can you be more specific about the steps to reproduce the issues with cluster import ? It seems to work fine for me. The ManagedClusterInfo is being matched only against cluster name, the namespace is not considered.

2022-11-23 12:32 UTC, rawagner commented
/retest

2022-11-23 19:42 UTC, merged