Fix and align ACM table filter cache
stolostron/console pull request #2307
Opened 2022-11-23 20:45 UTC by chenz4027

Signed-off-by: Maggie Chen <magchen@redhat.com>

2022-11-28 21:05 UTC, KevinFCormier requested changes
What happens if two different tables use the same ID for their filters? As a developer, my intuition would tell me that the IDs only need to be unique for a given table.

I found a few issues.

1. It seems `initialFilters` is not taking precedence. There is a feature on the GRC Overview page on the Policy violations card where if you click the legend for violations, you get taken to the policies table with a filter applied. If I visit the table first and filter by something else, like namespace, then my filter based on violations will not work.
2. If the JSON in the local storage is not well-formed, the table will crash.
3. If I filter by namespaces in the policies table, then the namespace gets deleted, the filter gives me 0 results, and it still counts the namespace filter as being present, even though it is not shown.

![image](https://user-images.githubusercontent.com/42188127/204380842-c37f2796-6e68-4f1f-b499-6b946c98325f.png)

2022-11-28 21:30 UTC, chenz4027 commented
Thanks @KevinFCormier 

What happens if two different tables use the same ID for their filters? As a developer, my intuition would tell me that the IDs only need to be unique for a given table.
Should we make it unique then?


It seems initialFilters is not taking precedence. There is a feature on the GRC Overview page on the Policy violations card where if you click the legend for violations, you get taken to the policies table with a filter applied. If I visit the table first and filter by something else, like namespace, then my filter based on violations will not work.
Yep I actually made it on purpose. Was debating whether we should make initialFilter first or cached filter first. Discussed with Dale and he looked into the code and he wasn't sure whether GRC update the URL for the table filters (we weren't able to find any code that would do that). Given that I move cache first over preset. However, I can move the sequence so that if there's any initial Filter, we would always render that instead of cache. Or maybe we render both?

If the JSON in the local storage is not well-formed, the table will crash.
Yep that's correct, I wonder what's the best approach for this issue? Ideally, user interactions should be okay as the cache are stored properly. However, if the user modify the cache in developer mode, I don't think we have a way to prevent it?


If I filter by namespaces in the policies table, then the namespace gets deleted, the filter gives me 0 results, and it still counts the namespace filter as being present, even though it is not shown.
Ok this is for sure an issue, will look into it.

2022-12-02 19:22 UTC, chenz4027 commented on frontend/src/ui-components/AcmTable/AcmTable.tsx
> +        existingFilter = JSON.parse(cachedFilter)
retest

2022-12-02 19:28 UTC, chenz4027 commented on frontend/src/ui-components/AcmTable/AcmTable.tsx
> +            localStorage.removeItem(id)
prefix ids

2022-12-02 19:38 UTC, chenz4027 commented on frontend/src/ui-components/AcmTable/AcmTable.tsx
> +                    const filterCache = JSON.parse(localStorage.getItem(id) as string)
make it a common component

2022-12-05 19:47 UTC, dhaiducek commented
LGTM! Thanks for the updates, @chenz4027! And for reminding me why we have the initial table filtering in GRC! 😬 

(I had forgotten why we had it and was wondering just now whether it should be removed, but I think it's helpful to be able to construct a shareable URL that filters the GRC table for users.)

2022-12-05 22:40 UTC, KevinFCormier commented
/lgtm

2022-12-05 23:34 UTC, merged