Disable setting remediationAction and severity for Gatekeeper policy templates
stolostron/console pull request #2788
Opened 2023-04-19 20:24 UTC by mprahl

This disables the remediationAction and severity options in the policy templates section of the policy wizard when it is a Gatekeeper constraint or ConstraintTemplate.

Instead, text is displayed that tells the user to use the YAML editor to make modifications.

Relates:
https://issues.redhat.com/browse/ACM-4808

2023-04-19 20:25 UTC, mprahl commented
@dockerymick could you please review the new text of "Gatekeeper policy templates must be customized through the YAML editor."?

/cc @dhaiducek @JustinKuli @yiraeChristineKim

2023-04-20 17:58 UTC, dhaiducek requested changes

2023-04-20 17:58 UTC, dhaiducek commented on frontend/src/resources/policy.ts
> +      remediationAction?: string
Current linting error:
```
error TS2322: Type 'string | undefined' is not assignable to type 'string'.
Type 'undefined' is not assignable to type 'string'. 
```
It looks like having `remediationAction` optional is causing this assignment to be upset?
https://github.com/stolostron/console/blob/9f5340910630f9541ed0ae69c90c29c0dfa18f98/frontend/src/routes/Governance/common/util.tsx#L484

2023-04-21 17:38 UTC, dockerymick approved these changes
Made a few suggestions

2023-04-21 17:38 UTC, dockerymick commented on frontend/public/locales/en/translation.json
> +  "Gatekeeper policy templates must be customized through the YAML editor.": "Gatekeeper policy templates must be customized through the YAML editor.",
```suggestion
  "Gatekeeper policy templates must be customized through the YAML editor.": "Gatekeeper policy templates must be customized using the YAML editor.",
```

2023-04-21 17:38 UTC, dockerymick commented on frontend/src/wizards/Governance/Policy/PolicyWizard.tsx
> +            <Text>{t('Gatekeeper policy templates must be customized through the YAML editor.')}</Text>
```suggestion
            <Text>{t('Gatekeeper policy templates must be customized using the YAML editor.')}</Text>
```

2023-04-21 17:38 UTC, dockerymick commented on frontend/src/wizards/Governance/Policy/policyWizard.test.tsx
> +    await waitForText('Gatekeeper policy templates must be customized through the YAML editor.', true)
```suggestion
    await waitForText('Gatekeeper policy templates must be customized using the YAML editor.', true)
```

2023-04-24 12:39 UTC, dockerymick approved these changes
Looks good to me

2023-04-24 13:44 UTC, mprahl commented
@KevinFCormier could you please "approve" this PR?

2023-04-24 13:48 UTC, KevinFCormier commented
/approve

2023-04-24 14:21 UTC, merged