ACM-5191 Console-crashes-templates-imetadata.name
stolostron/console pull request #2829
Opened 2023-05-02 14:14 UTC by jeswanke

Signed-off-by: John Swanke <jswanke@redhat.com>

2023-05-02 14:37 UTC, KevinFCormier commented on frontend/src/App.css
> +  width: 400px !important;
Did you mean to include this?

2023-05-02 15:06 UTC, jeswanke commented on frontend/src/App.css
> +  width: 400px !important;
oop

2023-05-02 15:27 UTC, KevinFCormier approved these changes

2023-05-02 17:25 UTC, KevinFCormier commented
/test unit-tests-sonarcloud

2023-05-04 16:32 UTC, KevinFCormier requested changes
There are a bunch of untranslated strings hiding in here. Will open an issue to deal with those later, but for now, just asking for a slight adjustment to the wording.

2023-05-05 01:22 UTC, KevinFCormier commented
/lgtm

2023-05-05 01:48 UTC, merged