Add `tolerations` to `Placement` for GRC
stolostron/console pull request #3337
Opened 2024-03-04 22:27 UTC by dhaiducek

Policy and PolicySets should not respond to unreachable clusters, so we need to add tolerations to Placement by default. Tolerations didn't exist previously, so I've added them to `PlacementSection` also.

ref: https://issues.redhat.com/browse/ACM-10200

2024-03-04 22:27 UTC, dhaiducek commented
/hold for reviews

/cc @mprahl @yiraeChristineKim

2024-03-05 14:43 UTC, yiraeChristineKim commented on frontend/src/wizards/Placement/PlacementSection.tsx
> +                'ClusterSets failed to load. Verify that there are ClusterSets bound to your selected namespace.'
Should translate to diff langs?

2024-03-05 14:44 UTC, yiraeChristineKim commented on frontend/src/wizards/Placement/PlacementSection.tsx
> +                'ClusterSets failed to load. Verify that there are ClusterSets bound to your selected namespace.'
```
"i18n:fix:frontend": "cd frontend && npm run i18n:fix --",
```

2024-03-05 18:57 UTC, yiraeChristineKim approved these changes

2024-03-06 18:35 UTC, yiraeChristineKim commented
/approve

2024-03-07 01:42 UTC, dhaiducek commented
Please take another look. I've made some updates:
- Changed the `tolerations` property to `defaultPlacementSpec` to provide additional flexibility for the future
- Enabled and edited a previously commented-out "description" (to be reviewed also by the Doc team)
- Updated some tooltip wording (the ClusterSet tooltip had been copied from Label expressions so was inaccurate)
- Moved the ClusterSet alert up for visibility and in an attempt to decouple it from the ClusterSets field.

2024-03-07 15:23 UTC, dockerymick requested changes
left some suggestions

2024-03-07 15:23 UTC, dockerymick commented on frontend/src/wizards/Placement/PlacementSection.tsx
> +      description="Placement selects clusters from the cluster sets which have been bound to the resource namespace. An empty Placement returns all available clusters from all bound cluster sets."
Use Placement resources to select clusters from the cluster sets that you have bound to the resource namespace. An empty Placement returns all available clusters from all bound cluster sets.

2024-03-07 15:23 UTC, dockerymick commented on frontend/public/locales/en/translation.json
> +  "Select cluster sets from which to select clusters. If no cluster sets are selected, all clusters will be selected from all cluster sets bound to the namespace.": "Select cluster sets from which to
```suggestion
  "Select cluster sets from which to select clusters. If you do not select a cluster set, all clusters are selected from all cluster sets bound to the namespace.": "Select cluster sets from which to select clusters. If you do not select a cluster set, all clusters are selected from all cluster sets bound to the namespace.",
```

2024-03-07 15:39 UTC, dhaiducek commented
/unhold

2024-03-07 15:40 UTC, dhaiducek commented
Thanks for the reviews, all! I think all relevant parties have reviewed this PR, so it should be good to re-review and merge.

2024-03-07 15:43 UTC, mprahl approved these changes

2024-03-07 15:43 UTC, yiraeChristineKim approved these changes

2024-03-07 15:55 UTC, dhaiducek commented
...and by "ready", I mean as soon as I fix the linting... 🤦‍♂️

2024-03-07 15:59 UTC, dhaiducek commented
Obligatory screenshots:
![image](https://github.com/stolostron/console/assets/19750917/9ba5da65-1066-4f2f-994b-a4ad4342fab6)
![image](https://github.com/stolostron/console/assets/19750917/9c24fae3-27c0-4032-a7f9-981d01100d35)

2024-03-07 16:05 UTC, dockerymick approved these changes

2024-03-07 16:20 UTC, merged

2024-03-12 15:18 UTC, dhaiducek commented
/cherry-pick release-2.10