add availability options step for kubevirt
stolostron/console pull request #3919
Opened 2024-10-01 12:45 UTC by robdolares

related issue: https://issues.redhat.com/browse/ACM-13678

2024-10-24 15:36 UTC, robdolares commented
@KevinFCormier - could you take a look when you get a moment.  The issue I am having is that the yaml is not being updated initially or immediately after making a change to the options.  After making change to another form field outside of the availability options step, they will update.  So in the end at least we are seeing what we want, just have to iron out the state issues:
<kbd>
<img width="1168" alt="Screenshot 2024-10-24 at 11 25 46 AM" src="https://github.com/user-attachments/assets/1bb056e4-e2c9-4d26-9dff-54ce8d602e2b">
</kbd>

2024-10-24 20:17 UTC, KevinFCormier commented
> @KevinFCormier - could you take a look when you get a moment. The issue I am having is that the yaml is not being updated initially or immediately after making a change to the options. After making change to another form field outside of the availability options step, they will update. So in the end at least we are seeing what we want, just have to iron out the state issues: <img alt="Screenshot 2024-10-24 at 11 25 46 AM" width="1168" src="https://private-user-images.githubusercontent.com/10394596/379839516-1bb056e4-e2c9-4d26-9dff-54ce8d602e2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4MDA4OTYsIm5iZiI6MTcyOTgwMDU5NiwicGF0aCI6Ii8xMDM5NDU5Ni8zNzk4Mzk1MTYtMWJiMDU2ZTQtZTJjOS00ZDI2LTlkZmYtNTRjZThkNjAyZTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDIwMDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNzI2ODY0NzQ1MjdkODBhN2U1YTU2Y2Q0NzEwMTY5N2E4NzgwZTI0ZGY4MWRjNDI2ZDBmN2EwNzUzM2FkMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BzzgM2_T9coad6vQ5wDopmerboIPiJjrQanf57CKFcI">

You were using the TimeWindow component as a reference implementation, but you missed a key part of it. See line 513.
https://github.com/stolostron/console/blob/main/frontend/src/routes/Applications/CreateApplication/Subscription/common/TimeWindow/index.js#L484-L515

You might notice in the control data that when we use a custom component, we do not provide any properties for it:
```
{
      id: 'availabilityOptions',
      type: 'custom',
      component: <AvailabilityOptionsForm />,
      active: []
}
```

So how does your component get the `control` property? Temptifly doesn't use the component you provided directly, but it clones it and provides several props. See https://github.com/stolostron/console/blob/main/frontend/src/components/TemplateEditor/controls/ControlPanel.js#L573-L606

One of these props is a `handleChange` function which you can call to tells temptifly to update the YAML editor.

I will leave additional comments inline.

2024-10-24 20:44 UTC, KevinFCormier requested changes
A couple minor inline comments.

After playing with this, I think I am more inclined to include the custom component on the first step, with *Cluster details*. Perhaps just before the *Additional labels* field. I think this is a setting most users will just leave as the default, so adding an extra step feels like overkill.

The alignment is off between the labels and the radio buttons though, and this will be more apparent if these controls are moved to be on the same step as other controls. I noticed though that we do have a control that uses radio buttons (the 'boolean' control) which has better alignment:

![image](https://github.com/user-attachments/assets/51197aa0-d133-4905-8f1b-0894d96bbead)
![image](https://github.com/user-attachments/assets/0d3e10ce-562a-448e-9929-d3b7878d7bd1)

2024-10-24 20:44 UTC, KevinFCormier commented on frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/AvailiabilityOptionsForm.tsx
Please correct the spelling error in the name of this file, and move it to an appropriate location. Although the Handlebars template file is under an `assisted-installer` directory, this flow has nothing to do with Assisted Installer.

2024-10-24 20:44 UTC, KevinFCormier commented on frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/assisted-installer/AvailiabilityOptionsForm.tsx
> +  }
You could set this in the control data instead of setting `active: []`.

2024-10-30 13:15 UTC, KevinFCormier commented on frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/AvailabilityOptionsForm.tsx
> +    { term: t('Infrastructure availability policy'), desc: infra },
I think the `desc` should be mapped to the translated display value here.

2024-11-01 22:14 UTC, KevinFCormier requested changes
Just a bit of cleanup needed. I will test out as well, but the code looks good otherwise.

2024-11-01 22:14 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +  "Single Replica": "Single Replica",
Duplicate casing

2024-11-01 22:14 UTC, KevinFCormier commented on frontend/public/locales/en/translation.json
> +  "Highly Available": "Highly Available",
Duplicate casing

2024-11-01 22:14 UTC, KevinFCormier commented on frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/AvailabilityOptionsForm.tsx
> +  const infraDesc: string = infra === 'HighlyAvailable' ? t('Highly Available') : t('Single Replica')
Exact same code repeated twice (and casing issue). Please extract to helper function.

2024-11-01 22:14 UTC, KevinFCormier commented on frontend/src/routes/Infrastructure/Clusters/ManagedClusters/CreateCluster/components/AvailabilityOptionsForm.test.tsx
> +  })
I expect this is not needed for coverage (since the next test renders the same thing), so I don't think we need a snapshot test here. Can we remove?

2024-11-02 00:14 UTC, KevinFCormier commented
/lgtm

2024-11-02 00:18 UTC, merged